{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "lamp.fullname" . }}-app
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.ingress.ssl }}
    cert-manager.io/cluster-issuer: letsencrypt-{{ template "lamp.fullname" . }}
    {{- end }}
    {{- if .Values.ingress.htpasswdString }}
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: {{ template "lamp.fullname" . }}
    ingress.kubernetes.io/auth-realm: "Authenticate"
    {{- end }}
    {{- if .Values.ingress.subdomainWWW }}
    ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(.*)$ $scheme://www.{{ template "lamp.domain" . }}$1;
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations }}
    {{- end }}
spec:
  {{- if .Values.ingress.ssl }}
  tls:
  - secretName: {{ template "lamp.fullname" . }}-tls-app
    hosts:
    - {{ template "lamp.domain" . }}
  {{- end }}
  rules:
  - host: {{ template "lamp.domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "lamp.fullname" . }}
          servicePort: {{ .Values.service.HTTPPort }}
{{- end }}
